// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjDfTXlvqjb_FPUXixs3lpJ2j4jleDUjo',
    appId: '1:247497726685:web:3d4a428445e9903776d934',
    messagingSenderId: '247497726685',
    projectId: 'my-music-app-6e6d5',
    authDomain: 'my-music-app-6e6d5.firebaseapp.com',
    storageBucket: 'my-music-app-6e6d5.firebasestorage.app',
    measurementId: 'G-KRRZ0TN31P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTfnLGhL3yYaGVJhT9cPBQBxUbYwjgFw',
    appId: '1:247497726685:android:f48456d8f7a7b4dd76d934',
    messagingSenderId: '247497726685',
    projectId: 'my-music-app-6e6d5',
    storageBucket: 'my-music-app-6e6d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bItDfR9j_qN8K5wyCCgY164m_2PMZwI',
    appId: '1:247497726685:ios:c4838cb52a7de17c76d934',
    messagingSenderId: '247497726685',
    projectId: 'my-music-app-6e6d5',
    storageBucket: 'my-music-app-6e6d5.firebasestorage.app',
    iosClientId: '247497726685-rvc9ncis04h1782hb9fosst23ofgdslq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMusicPlayers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8bItDfR9j_qN8K5wyCCgY164m_2PMZwI',
    appId: '1:247497726685:ios:c4838cb52a7de17c76d934',
    messagingSenderId: '247497726685',
    projectId: 'my-music-app-6e6d5',
    storageBucket: 'my-music-app-6e6d5.firebasestorage.app',
    iosClientId: '247497726685-rvc9ncis04h1782hb9fosst23ofgdslq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMusicPlayers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjDfTXlvqjb_FPUXixs3lpJ2j4jleDUjo',
    appId: '1:247497726685:web:88ee854607fa77a276d934',
    messagingSenderId: '247497726685',
    projectId: 'my-music-app-6e6d5',
    authDomain: 'my-music-app-6e6d5.firebaseapp.com',
    storageBucket: 'my-music-app-6e6d5.firebasestorage.app',
    measurementId: 'G-FGER31MBLX',
  );
}
